---
name: Products Watch CI
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  ci:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Node Build
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Clean and install dependencies
        run: npm ci

      - name: Run project tests
        run: npm test
...